site_name: Ragnos Docs
repo_url: https://github.com/cgarciagl/ragnos
edit_uri: "" # Elimina el botón de edición

theme:
  name: mkdocs
  sticky_navigation: true
  collapse_navigation: false
  titles_only: false
  highlightjs: true
  hljs_style: panda-syntax-dark

extra_css:
  - css/ragnos_style.css

extra_javascript:
  - js/particles.js

plugins:
  - search
  - mermaid2:
      version: "10.6.1"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

nav:
  - Inicio: index.md
  - Fundamentos:
      - Instalación: fundamentos/instalacion.md
      - Primeros Pasos: fundamentos/primeros_pasos.md
      - Configuración: fundamentos/configuracion.md
      - Generador CLI: fundamentos/plantilla.md
  - Datasets y Modelos:
      - Creando Datasets: datasets/datasets.md
      - Referencia de Campos: datasets/campos.md
      - Consultas Avanzadas (RQuery): datasets/guia_RQueryController.md
      - Maestro-Detalle: datasets/maestro-detalle.md
  - Backend Avanzado:
      - Modo API: avanzado/guia_modo_api.md
      - Helpers y Utilidades: avanzado/helpers.md
      - Hooks y evento: avanzado/hooks.md
      - Autenticación: avanzado/autenticacion_integrada.md
      - Audit Log: avanzado/auditlog.md
      - Server Side Events: avanzado/server_side_events.md
      - Despliegue: avanzado/despliegue.md
  - Frontend y Reportes:
      - Personalización UI: frontend/personalizacion_ui.md
      - Reportes Simples: frontend/reportes_simples.md
      - Funciones JavaScript: frontend/funciones_javascript.md
