name: Publicar Web y Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Instalar dependencias
        run: |
          pip install mkdocs-material
          pip install mkdocs-mermaid2-plugin
          pip install mkdocs-static-i18n

      - name: Construir y Preparar Sitio
        run: |
          # 1. Crear la carpeta final 'public'
          mkdir -p public

          # 2. Copiar tu Landing Page (carpeta web) a public
          cp -r web/* public/

          # 3. Entrar a la carpeta 'documentacion', construir y salir
          cd documentacion
          mkdocs build
          cd ..

          # NOTA: Por defecto, mkdocs crea una carpeta llamada 'site' 
          # justo donde está el mkdocs.yml.

          # 4. Mover esa carpeta 'site' a 'public/docs'
          mv documentacion/site public/docs

      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
